FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /src


COPY . .
WORKDIR /src/src/Pusula.Training.HealthCare.DbMigrator
RUN dotnet publish "Pusula.Training.HealthCare.DbMigrator.csproj" -c Release -o /app/publish


FROM base AS final

WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Pusula.Training.HealthCare.DbMigrator.dll"]
